### PR TITLE
Fix C++11 compilation flags

### LINKED ISSUE #17: C++11 option overwritten by C++03 option in CMake
This `--cpp` here overwrites the `--cpp11` option:
https://github.com/ARMmbed/target-mbed-armcc/blob/master/CMake/Platform/mbedOS-ARMCC-CXX.cmake#L17

Removing it enables the full use of C++11, e.g. lambda functions etc.

Thanks to @pan- for finding this out.

@bogdanm @bremoran @autopulated

### PR DESCRIPTION
**Pull request by bogdanm**
The flag in CMake/toolchain.cmake was overwritten in
CMake/Platform/mbedOS-ARMCC-CXX.cmake. This commit removes the
overwrite.

Tested by compiling mbed-drivers and core-util with k64f-armcc.

Fixes #17

### CODE REVIEW

**Comment by bogdanm** [comment]
@niklas-arm

**Comment by niklas-arm** [comment]
:+1:. This works for me on Linux.

**Comment by bogdanm** [comment]
Ah, good point, I'll test it on Windows too.

**Comment by niklas-arm** [comment]
Please also test if this compiles on windows with this fix:
```cpp
typedef void(*void_function_t)(void);

auto foo = []() { printf("Lambda's (auto) work in ARMCC\n"); };
void_function_t foo2 = []() { printf("Lambda's (function pointer cast) work in ARMCC\n"); };

// then call functions somewhere
foo();
foo2();
```
CC @0xc0170

**Comment by bogdanm** [comment]
@niklas-arm, compiled regular `mbed-drivers` and `mbed-drivers` with your code added to one of its tests under Windows with armcc5.05. Everything looks good.

**Comment by niklas-arm** [comment]
Very nice! I can remove the limitations on lambda functions on ARMCC from `utest` documentation then.
Yay \o/.

**Comment by 0xc0170** [comment]
+1, tested on windows with armcc 5.06

**Comment by bogdanm** [comment]
OK, since everything looks good, I'm going to merge this.

**Comment by bogdanm** [comment]
I'm not an owner for this module. @autopulated or @bremoran: please publish a new version.

**Comment by autopulated** [comment]
:+1: will do

**Comment by autopulated** [comment]
published 1.0.1, also added you as an owner.

**Comment by bogdanm** [comment]
Thanks! :ok_hand:

**Pull request merged**
